services:
  bibliocafe-database:
    image: mongo
    ports: 
      - "27017:27017"
  bibliocafe-backend:
    build: backend/
    environment: 
      - PORT=3001
      - DATABASE_URL=mongodb://host.docker.internal:27017/bibliocafe
    ports:
      - '3001:3001'
    depends_on:
      - bibliocafe-database
  bibliocafe-frontend:
    build: 
      context: frontend/
      args: 
        VITE_API_URL: http://localhost:3001/api/v1
    ports:
      - '3000:80'
    depends_on:
      - bibliocafe-backend