name: Deploy Bibliocafe

on:
  push:
    branches:
      - main


jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-frontend.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GOOGLECLOUD_SERVICE_ACCOUNT }}
          credentials_json: ${{ secrets.GOOGLECLOUD_CREDENTIALS }}
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bibliocafe-backend:latest
      - id: deploy-backend
        name: Deploy backend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: bibliocafe-backend
          image: ${{ secrets.DOCKERHUB_USERNAME }}/bibliocafe-backend:latest }}
          region: ${{ secrets.GOOGLECLOUD_REGION }}
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bibliocafe-frontend:latest
          build-args: VITE_BACKEND_URL=${{ steps.deploy-backend.outputs.url }}/api/v1
      - id: deploy-frontend
        name: Deploy frontend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: bibliocafe-frontend
          image: ${{ secrets.DOCKERHUB_USERNAME }}/bibliocafe-frontend:latest
          region: ${{ secrets.GOOGLECLOUD_REGION }}