name: Bibliocafe Frontend CI

# Listen to events
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Job to run linter and build
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        # Run tests on multiple node versions
        node-version: [18.x, 20.x, 22.x]
    defaults:
      run:
         working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run linter 
        run: npm run lint
      - name: Build
        run: npm run build